### ISSUE TITLE
Unable to build with libpciaccess on Ubuntu 18.04

### ISSUE THREAD

**Issue by ghost** [rsa9000/atheepmgr#2]
I have `libpciaccess0` and `libpciaccess-dev` installed, and building `atheepmgr` then fails with the following errors:

```
cc -Wall  -DCONFIG_CON_PCI -DCONFIG_CON_MEM -c atheepmgr.c -o atheepmgr.o
cc -Wall  -DCONFIG_CON_PCI -DCONFIG_CON_MEM -c con_file.c -o con_file.o
cc -Wall  -DCONFIG_CON_PCI -DCONFIG_CON_MEM -c eep_5211.c -o eep_5211.o
cc -Wall  -DCONFIG_CON_PCI -DCONFIG_CON_MEM -c eep_5416.c -o eep_5416.o
cc -Wall  -DCONFIG_CON_PCI -DCONFIG_CON_MEM -c eep_9285.c -o eep_9285.o
cc -Wall  -DCONFIG_CON_PCI -DCONFIG_CON_MEM -c eep_9287.c -o eep_9287.o
cc -Wall  -DCONFIG_CON_PCI -DCONFIG_CON_MEM -c eep_9300.c -o eep_9300.o
cc -Wall  -DCONFIG_CON_PCI -DCONFIG_CON_MEM -c eep_common.c -o eep_common.o
cc -Wall  -DCONFIG_CON_PCI -DCONFIG_CON_MEM -c hw.c -o hw.o
cc -Wall  -DCONFIG_CON_PCI -DCONFIG_CON_MEM -c utils.c -o utils.o
cc -Wall   -DCONFIG_CON_PCI -DCONFIG_CON_MEM -c con_pci.c -o con_pci.o
cc -Wall  -DCONFIG_CON_PCI -DCONFIG_CON_MEM -c con_mem.c -o con_mem.o
cc -lpciaccess atheepmgr.o con_file.o eep_5211.o eep_5416.o eep_9285.o eep_9287.o eep_9300.o eep_common.o hw.o utils.o con_pci.o con_mem.o -o atheepmgr
con_pci.o: In function `pci_device_init':
con_pci.c:(.text+0x1e3): undefined reference to `pci_device_map_range'
con_pci.o: In function `pci_device_cleanup':
con_pci.c:(.text+0x2ae): undefined reference to `pci_device_unmap_range'
con_pci.o: In function `pci_init':
con_pci.c:(.text+0x5f1): undefined reference to `pci_system_init'
con_pci.c:(.text+0x633): undefined reference to `pci_slot_match_iterator_create'
con_pci.c:(.text+0x676): undefined reference to `pci_device_next'
con_pci.c:(.text+0x686): undefined reference to `pci_iterator_destroy'
con_pci.c:(.text+0x6c4): undefined reference to `pci_device_probe'
con_pci.c:(.text+0x744): undefined reference to `pci_system_cleanup'
con_pci.o: In function `pci_clean':
con_pci.c:(.text+0x77c): undefined reference to `pci_system_cleanup'
collect2: error: ld returned 1 exit status
Makefile:47: recipe for target 'atheepmgr' failed
make: *** [atheepmgr] Error 1
```

**Comment by rsa9000** [comment]
Hello! Thank you for your report. I am unable to investigate the situation now. I will return in a week or so.

**Comment by rsa9000** [comment]
@kkeijzer, please try the attached patch for Makefile, it should fix the linking issue.
[Makefile.patch.txt](https://github.com/rsa9000/atheepmgr/files/3448870/Makefile.patch.txt)

**Comment by ghost** [comment]
This fixes the issue. Thanks!

**Comment by rsa9000** [comment]
@kkeijzer, I would like to commit this fix, so may I use you name/mail in 'Reported-and-tested-by:' tag?

**Comment by ghost** [comment]
Of course you may!
